### ISSUE TITLE
Chunked Data

### ISSUE THREAD

**Issue by zane-shus** [mwgg/iracing-php#3]
How do I use chunked data for something like a world record?

`$results = $iracing->stats->world_records(1,1);`

```
Warning: Undefined property: stdClass::$link in /var/www/html/vendor/mwgg/iracing-php/src/Api.php on line 135

Fatal error: Uncaught TypeError: iRacingPHP\Api::retrieveData(): Argument #1 ($url) must be of type string, null given, called in /var/www/html/vendor/mwgg/iracing-php/src/Api.php on line 135 and defined in /var/www/html/vendor/mwgg/iracing-php/src/Api.php:100
Stack trace:
#0 /var/www/html/vendor/mwgg/iracing-php/src/Api.php(135): iRacingPHP\Api->retrieveData(NULL)
#1 /var/www/html/vendor/mwgg/iracing-php/src/Data/Stats.php(173): iRacingPHP\Api->request('/stats/world_re...', Array)
#2 /var/www/html/api_test.php(10): iRacingPHP\Data\Stats->world_records(1, 1)
#3 {main}
  thrown in /var/www/html/vendor/mwgg/iracing-php/src/Api.php on line 100
/var/www/html #
```

ta

**Comment by mwgg** [comment]
Fixed with 6f4695b4829b9aa57a18ca4d4c2238e0c6186f4c (v1.4.0).
